name: 'Amazon ECS "Update Container Property in Task Definition" Action for GitHub Actions'
description: 'Updates a given container property in an Amazon ECS task definition JSON file, creating a new task definition file.'
branding:
  icon: 'cloud'
  color: 'orange'
inputs:
  task-definition:
    description: 'The path to the ECS task definition JSON file'
    required: true
  container-name:
    description: 'The name of the container defined in the containerDefinitions section of the ECS task definition'
    required: true
  property-name:
    description: 'The property name to update'
    required: true
  value:
    description: 'The new value of the property'
    required: true
outputs:
  task-definition:
    description: 'The path to the rendered task definition file'
runs:
  using: 'node12'
  main: 'dist/index.js'
